name: zabbix-lab

services:
  postgres:
    image: ${POSTGRES_IMAGE}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - zbx-core
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:${ZABBIX_TAG}
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - zbx-core

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:${ZABBIX_TAG}
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: postgres            # flux frontend -> base (5432)
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ZBX_SERVER_HOST: zabbix-server      # flux frontend -> serveur (10051)
      ZBX_SERVER_NAME: Skills Lab         # nom affiché dans l'interface
      PHP_TZ: Europe/Paris
    ports:
      - "127.0.0.1:8080:8080"             # boucle locale uniquement, jamais 0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy
      zabbix-server:
        condition: service_started
    networks:
      - zbx-core

networks:
  zbx-core:

volumes:
  pgdata:
